"""Add exit_plan to positions

Revision ID: bb70a33be8af
Revises: 69cdf9139a79
Create Date: 2025-11-03 13:53:11.160967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb70a33be8af'
down_revision = '69cdf9139a79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('exit_plan', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'exit_plan')
    # ### end Alembic commands ###
